// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2I5yN-bUiXl8E9Ltc6amwaXoltqDrAe4',
    appId: '1:167904333192:web:4b90ef93d0d22305ccbe3d',
    messagingSenderId: '167904333192',
    projectId: 'ritik-firebase',
    authDomain: 'ritik-firebase.firebaseapp.com',
    storageBucket: 'ritik-firebase.appspot.com',
    measurementId: 'G-1DL3GR5RLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKBgi_s0izncuAgEA5Cw64AWLZZ6q1xLU',
    appId: '1:167904333192:android:d70ec36cf1ffefd4ccbe3d',
    messagingSenderId: '167904333192',
    projectId: 'ritik-firebase',
    storageBucket: 'ritik-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYqAj1VysUYl5QAQPPNERexzU-qwsq_rQ',
    appId: '1:167904333192:ios:e12e7f240b19fd8eccbe3d',
    messagingSenderId: '167904333192',
    projectId: 'ritik-firebase',
    storageBucket: 'ritik-firebase.appspot.com',
    iosClientId: '167904333192-9vqgpvfn004s09ocppcd9khj9io2rj4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYqAj1VysUYl5QAQPPNERexzU-qwsq_rQ',
    appId: '1:167904333192:ios:e12e7f240b19fd8eccbe3d',
    messagingSenderId: '167904333192',
    projectId: 'ritik-firebase',
    storageBucket: 'ritik-firebase.appspot.com',
    iosClientId: '167904333192-9vqgpvfn004s09ocppcd9khj9io2rj4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioApp',
  );
}
